#! /usr/bin/bash
sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl
sudo apt install rig
sudo apt install 0ad
sudo apt install fnt
sudo apt install mpv
sudo apt install ffmpeg
